# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: detect-aws-credentials
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.30.0'
    hooks:
    -   id: yapf
-   repo: https://gitlab.com/iamlikeme/nbhooks
    rev: 1.0.0
    hooks:
    -   id: nb-ensure-clean
        exclude: Examples/Example.ipynb
-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: pytest tests -v -ra
        language: system
        types: [python]
        stages: [push]
# -   repo: https://github.com/pycqa/pylint
#     rev: 'pylint-2.6.0'
#     hooks:
#     -   id: pylint
#         args: [--errors-only]

